# Learn more about configuring your app at https://shopify.dev/docs/apps/tools/cli/configuration

client_id = "9672ffad7b8037a63f09f907c8398b54"
name = "PostPulse"
handle = "postpulse"
application_url = "https://marco-adrian-vbulletin-screenshot.trycloudflare.com"
embedded = true

[build]
include_config_on_deploy = true
automatically_update_urls_on_dev = true

[webhooks]
api_version = "2025-07"

  [[webhooks.subscriptions]]
  topics = [ "app/uninstalled" ]
  uri = "/webhooks/app/uninstalled"

  [[webhooks.subscriptions]]
  topics = [ "app/scopes_update" ]
  uri = "/webhooks/app/scopes_update"

[access_scopes]
# Learn more at https://shopify.dev/docs/apps/tools/cli/configuration#access_scopes
scopes = "write_products"

[auth]
redirect_urls = ["https://marco-adrian-vbulletin-screenshot.trycloudflare.com/auth/callback", "https://marco-adrian-vbulletin-screenshot.trycloudflare.com/auth/shopify/callback", "https://marco-adrian-vbulletin-screenshot.trycloudflare.com/api/auth/callback"]

[pos]
embedded = false
